[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Note: Netlify doesn't support WebSocket servers directly
# You'll need to deploy the WebSocket server separately
# Recommended: Use Railway or Render for the WebSocket server

[build.environment]
  NODE_VERSION = "18"
